### ISSUE TITLE
Add the boilerplate code for TODO list

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#15]
Add a boilerplate code for the TODO list segment of the site.
> A boilerplate code is basically a overview code, without any logic or implementations. At most the boilerplate code would be containing function initializations, with the body of the function contains a comment explaining the work that function is supposed to do.

Also currently you can also add a simple tabular form of html for the TODO list, with a button and a heading. The function triggers of the buttons should be left empty, with only the `required statement` of the function.

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu would you like to do this?

**Comment by Bbiswabasu** [comment]
Yeah sure.

**Comment by Raghwendra-Dey** [comment]
When could you expect to deliver the boilerplate code? Since untill this is done, others cant go ahead with their works.
Don't do too much on the boilerplate code. Keep it simple for now, we can always add more things later. Remember boilerplate code is just a skeleton code, not the actual code.
Also, how do you suggest to write this code, I mean should this be on the same `script.js` file, or add one more file dedicated towards the todo list things. I suggest the other one would be cleaner.

**Comment by Bbiswabasu** [comment]
I can do it by tomorrow 10 AM. I have already planned how to proceed but I need some time to present it in a good manner.
I think making a seperate todo_list.js would be better.
If someone else can deliver the boilerplate code earlier than the time I mentioned, you can surely assign them the task.

**Comment by Raghwendra-Dey** [comment]
Okay, thats fine. You take your time. I think you would be able to do this faster since, you are already familiar with the codebase, and have also done some work on this.
Yeah, go ahead with a separate `todo_list.js` file.

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu please open relevant issues for distribution of tasks on the boilerplate code of the TODO list feature. Break it into as simpler parts as possible.
Please clearly mention below them to give pull requests to the `todoList` branch instead of `master`.
