### ISSUE TITLE
Update button designs

### ISSUE THREAD

**Issue by tejan-singh** [Raghwendra-Dey/productivity_meter#19]
I would like to add modern design to buttons using bootstrap to make UI look better.

**Comment by prsingh061000** [comment]
@tejan-singh I can work on this issue

**Comment by Raghwendra-Dey** [comment]
@tejan-singh could you describle the design you are thinking of implementing, maybe if you have a photograph, or if you could draw them, it would be easier to visualise, before implementing them.

**Comment by aalokagrawal** [comment]
@Raghwendra-Dey  I can do that hover part and if you want some styling to make it look better I can do that too.Assign this issue to me.I would like to work on this one.

**Comment by Raghwendra-Dey** [comment]
@aalokagrawal you do the hovering thing. And let @tejan-singh handle the designing aspects of the buttons. Maybe you open one more issue regarding the hovering thing, and I would assign you that.

**Comment by tejan-singh** [comment]
Here! The Preview of buttons. 
https://codepen.io/tstejan/pen/WNGxQaY

**Comment by Raghwendra-Dey** [comment]
@tejan-singh It looks great!!  I think its already done, so please raise a PR by implementing it for this project.
