### ISSUE TITLE
Bind start and stop of first timer to second

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#2]
Bind `start` and `stop` of `Time Devoted` to the `Actual Time Used` so that whenever `Time Devoted` timer `starts`/`stops` it automatically does the same thing with `Actual Time Used` timer. But don't confuse it with the vice-versa of binding second with the first.

**Comment by squarecylinder** [comment]
Just uploaded a fix for this in PR! Hope that helps.

**Comment by Raghwendra-Dey** [comment]
Thanks a lot!! You are welcomed to contribute some more to this project. If you find some bug or think of any other feature which might be helpful, feel free to raise an issue.
