### ISSUE TITLE
Pop-up message 

### ISSUE THREAD

**Issue by kri-bhawna** [Raghwendra-Dey/productivity_meter#21]
We can let a pop-up message to appear whenever there will be any increment/decrement in the number of problems solved. This pop-up message can be featured to fade away automatically after a certain duration of time, say 5 sec.  
For increment we can use "Well done ! keep it up!" , and for decrement "Oops! you've got an extra problem to solve!".

**Comment by Raghwendra-Dey** [comment]
Also please add a pop up message for the `Go` button proposed in the diagram given in #20 . Maybe something like, `The clock is ticking, hurry up!!`

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna would you like to work on it?

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey  Sure, I can do that.

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna please consider adding the error message pop-up of #24 , after its assignee is done with it. I believe that won't take long, so, for the time being consider working for the problem counter thing only.
Also make the pop-up similar to what happens when we hover over `#24` above in github.

**Comment by kri-bhawna** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/63978409/101647056-4db55b80-3a5e-11eb-8e54-95961d13feb7.png)
![Screenshot (19)](https://user-images.githubusercontent.com/63978409/101647082-55750000-3a5e-11eb-8596-438f9e3382bb.png)

@Raghwendra-Dey Sir, please give your reviews regarding this format of the pop-ups to be displayed when +1 and -1 are clicked.

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey These pop-ups will be displayed for 3 seconds(including the fade away time) and will fade away after that.
These are displayed at the bottom right of the screen, in order to avoid any distraction for the user.
Also, I was thinking to add an alert which will be displayed if problem count is 0 and user clicks -1. 
Alert having the text "You are already at problem count zero." This alert can be displayed on the top of the screen, as it needs attention of user.
Please, give your feedback regarding  this.

**Comment by Raghwendra-Dey** [comment]
Yeah these notification things are nice, but keep them small and also add a cross option in the top right, so that the user can cancel the things by clicking em. Just like its there in codeforces.com .
Yeah, you can add this thing for the alreat as well. I don't think it would be good to change the position of the notification.
But still prepare the demo for both, we'll see later.

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey In reference to https://github.com/Raghwendra-Dey/productivity_meter/issues/21#issuecomment-739836245
Can you please clarify this ? I am not getting when actually do the pop up box has to appear for **Go** button, as per mentioned in above comment in #21 itself.

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna for now, you just add them for `+1, -1 and reset buttons`

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey Sir, I am done with +1,-1 and reset . Can I create a pull request for that?

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna please post the photos here once.

**Comment by kri-bhawna** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/63978409/102009583-62e00200-3d5e-11eb-8e43-33e4c22d9d24.png)
![Screenshot (22)](https://user-images.githubusercontent.com/63978409/102009585-67a4b600-3d5e-11eb-9fc2-606b4c3e47d5.png)
![Screenshot (23)](https://user-images.githubusercontent.com/63978409/102009587-67a4b600-3d5e-11eb-8e28-06f8cc6dd88e.png)
![Screenshot (24)](https://user-images.githubusercontent.com/63978409/102009588-683d4c80-3d5e-11eb-8ca2-293e0f3978e5.png)

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey I have added the cross icon in all of these, and it is having the hover effect of of red color. Also, have added the transition effect of fade off with different time intervals. Also, as per instructed previously I have reduced their sizes  .
Please give your feedback.

**Comment by Raghwendra-Dey** [comment]
> @Raghwendra-Dey I have added the cross icon in all of these, and it is having the hover effect of of red color. Also, have added the transition effect of fade off with different time intervals. Also, as per instructed previously I have reduced their sizes .
> Please give your feedback.

Hey @kri-bhawna they look great!! Please raise a PR, and I would review the changes and merge it afterwards.
