### ISSUE TITLE
Make all the blocks to contain the text which is shown above it and change its positioning

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#23]
Include the text of each block to include it. Try to also introduce a bit of bootstrap into the site with it, to give it responsiveness. Position the three blocks in the same row with the `difference block` in the middle, the `Time Devoted` on the right and `Actual Time Used` to the right of it.

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 would you like to work on it?

**Comment by Nishant2907** [comment]
Yes sure @Raghwendra-Dey, I can do it. For now I will finish the issue for header and footer by today night or tomorrow morning 
 and then I can work on this too. Thanks for considering me in this :)

**Comment by Nishant2907** [comment]
@Raghwendra-Dey , i think this issue has been already solved.

**Comment by Raghwendra-Dey** [comment]
Yeah more or less.
I think we can close this.
