### ISSUE TITLE
Add a text field with a Set button associated with it

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#24]
Add a text field where user can enter a number and after that if the `Set` button is pressed, which is associated on it, this action would set the value of a global variable `breakDur`, to the entered value. This issue is the part of the notification system we are trying to implement.
You can have a look at the diagram below for better understanding:

![IMG_20201207_164121](https://user-images.githubusercontent.com/45457947/101344234-2ec29800-38ab-11eb-985f-1566c8c9a786.jpg)

* You need to work with html, for adding this block, and a bit of javascript to make the trigger function of the `Set` button. 
* This is very similar to making a form which only contains a text field, with a submit button(here called `Set` button). 
* Also add a data validation for the text field values, since we are only expecting number values, to be entered.
* If the entered value is not a number then you just don't do anything, and print an error message to the `console.log` like, `Entered value should be a number`. 
* Default that variable value to 20 .
* Later on we can add a pop-up message to signify this error. This pop-up message thing would be taken care of by the #21 assignee.
* Don't worry much about the styling things, make it similar to the other blocks in the site. You can use there class. No need to mess around with the CSS for now.

Comment below if you need some more clarifications.
Make all the PRs related to this in the `notification` branch of this repo.

**Comment by Raghwendra-Dey** [comment]
@Lucky-321 would you like to work on this?

**Comment by Lucky-321** [comment]
> @Lucky-321 would you like to work on this?

Yes

**Comment by Raghwendra-Dey** [comment]
Untill when do you expect to deliver it. Any rough deadlines would be helpful to synchronise other aspects of the notification system.
And please name that global variable `breakDur` .

**Comment by Lucky-321** [comment]
I have included the pop-up message part with my code
