### ISSUE TITLE
Make a function to play sound

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#25]
Make a function which would play a notification sound, when both the timers are stopped, i.e. the user is on a long break and the elapsed time of long break crosses the time set in a global variable named `breakDur` given by #24  . You may need to start a new setInterval instance to keep track of this elapsed time between long breaks. Theres more of working with javascript in this issue. This is a part of the notification system of the notification system we are trying to develop.
Comment below if you need some more clarifications.
Make all the PRs related to this in the `notification` branch of this repo.

**Comment by Raghwendra-Dey** [comment]
@TusharDasMe would you like to work on this?

**Comment by ghost** [comment]
@Raghwendra-Dey  Sir, I would like to work on this issue. PLease clarify a bit more. Then I will work on it 
 
Thanks & Regards
Urvashi Anand

**Comment by TusharDasMe** [comment]
Ok tell me more about your requirement

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 you work on writing a function which would play a notification sound, whenever that is called.
And @TusharDasMe and you work on making a function which would print a message to the `console.log` when the time elapsed during the long break crosses the value set in the `breakDur` variable. Also you need to repeat the message after every 5 mins.
It would be like:
* print the message first time when the elapsed time crosses `breakDur` value.
* again print it next time after 5mins, again after 5mins.. and so on. untill the user starts both the timers once again, indicating, he is at work again. Its very similar to working of `alarm clock` and its snooze feature.

After you both are done, we would integrate both of these things along with #24 to make the notification system.
Let me close this issue and split it into two relevant issues.

Thank you!

**Comment by ghost** [comment]
Okay @Raghwendra-Dey  Sir I will work on it.
