### ISSUE TITLE
Hovering effect to the buttons 

### ISSUE THREAD

**Issue by ghost** [Raghwendra-Dey/productivity_meter#29]
As of now, there is no hovering effect on the buttons. So, I would like to add hovering effect. I am thinking of adding some transformation from low scale to high. It will look good. Please assign this issue to me @Raghwendra-Dey  Sir. 

Thanks & Regards
Urvashi Anand

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 could you elaborate on how exactly you are planning to make the hovering effect, and what are the design changes you are planning to make?
A diagram and a detailed explaination would be of great help.

**Comment by ghost** [comment]
I want to use 
.button{
transfrom=scale(09...);
}

.button:hover{
transform = scale(1....);
}
with some modifications in it like to reduce the opacity.
So that buttons will look real and performing after hovering.

**Comment by ghost** [comment]
@Raghwendra-Dey Sir, I want to make the hover effect on the Go buttons.
Also, I will think some other styling for the +1, -1 and reset buttons.
Can, I send more than 1 prs for the same issue?

**Comment by Raghwendra-Dey** [comment]
I still not get about the hovering effects. Like for the `Go` button mentioned in the #20 diagram? If yes then, it would be great then the assignee of it need not to worry about it.
Please elaborate about the hovering effects of other buttons, except `Go` button, like `+1`, `-1` etc. 

For the `Go` button, we can't make this as other buttons, we need to give it a look, which shows, whether is it currently `ON` or `OFF`. Maybe, you can show that button, a bit pressed when `ON`, and raised when `OFF` to be easily distinguishable.

> Can, I send more than 1 prs for the same issue?

No problem. Please open one more issue for the styling things you are talking about. then send two PRs for both of them. 

> I am thinking of adding some transformation from low scale to high. It will look good.

By styling things I mean these things.

**Comment by ghost** [comment]
So, @Raghwendra-Dey  Sir. Can I open one issue for the Go buttons and seperate issues for the other buttons as they will require unique styling. So, Can I close this one and open seperate.

**Comment by ghost** [comment]
After that I will just start working and send prs for all :)

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 Sure, Please close this and open two issues, one regarding the hovering of other buttons, and one regarding hovering of the `Go` button. Presently you focus on the hovering of the other buttons and #27 . Since, the `Go` button things can't be implemented unless #20 is resolved. For `Go` button, make an issue, and work on it later.

**Comment by ghost** [comment]
Okay @Raghwendra-Dey  Sir, Thank you :)
