### ISSUE TITLE
Styling for the +1 -1 and Reset buttons

### ISSUE THREAD

**Issue by ghost** [Raghwendra-Dey/productivity_meter#33]
@Raghwendra-Dey  Sir, As of now there is no hovering state, active state stylings for the +1 -1 and Reset buttons.
I would like to add more styling to these buttons. Please assign me this issue :)

Thanks & Regards
Urvashi Anand

**Comment by Raghwendra-Dey** [comment]
Please also consider giving a good styling to other buttons as well.
Like all the buttons of the `timers`. 
You can give the same hovering effects to all the buttons currently in the project.
Please comment below, if you need further explaination.

**Comment by ghost** [comment]
https://codepen.io/urvashi-code1255/pen/ExgyJoZ

This is the effect i was talking about @Raghwendra-Dey  Sir

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 Looks good to me. Implement it for the site.
