### ISSUE TITLE
Bug in actual time used

### ISSUE THREAD

**Issue by siddhant094** [Raghwendra-Dey/productivity_meter#34]
@Raghwendra-Dey 
Press GO of the time devoted option . wait for a few seconds and now stop the actual time used and the time devoted.
Now , press clear on the time devoted. The time on actual time used should also be cleared. However , this does not happen and I want to fix this bug.

**Comment by Raghwendra-Dey** [comment]
Okay you can link the clear of the `Time Devoted` to enforce its actions on `Actual Time Used` but don't do this other way round. It may be needed to clear only the `Actual Time Used`.

**Comment by siddhant094** [comment]
Yes Sure. Please assign me the issue.
