### ISSUE TITLE
Enforce a check on starting of second timer

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#4]
Since, it is logical that the `second timer` wont run when the first one is stopped. So enforce a check while starting the `second timer` and only do so if the `first timer` is already running.

**Comment by Raghwendra-Dey** [comment]
@squarecylinder Check this out, if possible.

**Comment by squarecylinder** [comment]
So, are you trying to make it so the `second timer` only runs when the `first timer` is going? If thats the case, and we already bound the first timer buttons to the second, why not just remove the start/stop from the `second timer`? Unless I am misinterpreting what you are asking for.

**Comment by Raghwendra-Dey** [comment]
No no, Actually the main motto of this project is to enable us to keep track of small small breaks and time wastage during our studies. So the first timer is the time we think we are studying and the second one is when we are actually studying. So, the first timer is bound to the second one, cool. Now, obviously you are studying only a subset of the time you think you are studying. So if the second timer is running when the first one is stopped, it is logically incorrect. But we still need the second timer's controls to stop it when we are on small breaks.

**Comment by rsriramc** [comment]
I can take up on this. 
But, I think a better option would be that the **start of second button will start the first one** **only in the case** when **both are stopped**. 
That simply means that the person has **just started studying** or **started again, from a long break**. This would also by-pass the necessity of clicking two buttons for those who want to start both timers at once.

**Comment by Raghwendra-Dey** [comment]
@ravisrc sorry i think theres a bit of confusion.
Here the `first timer` is the `Time Devoted` timer and the `second timer` is the `Actual Time Used` timer.
Now the first timer would run even when you are taking small breaks, but the second timer would stop during the small breaks.
In simple words, you can say that logically `first timer time >= second timer timer` always.
And the `first timer` is already linked to affect `second timer` whenever it is switched on or off (#3). You can try it [here](https://raghwendra-dey.github.io/productivity_meter/) Try to switch on and off only the `first timer`, and it would enforce that action on the second timer.
What this issue is talking about is that its illogical for second timer to run, even when the first one is stopped, so you just have to implement this condition.
You can read more about the working of the project [here](https://github.com/Raghwendra-Dey/productivity_meter#usage).
Please let me know, if you want me to elaborate on something.
