### ISSUE TITLE
Overflow-x after the addition of footer

### ISSUE THREAD

**Issue by ghost** [Raghwendra-Dey/productivity_meter#42]
![productivityMeter](https://user-images.githubusercontent.com/63122133/101514912-ca373400-39a3-11eb-9a50-cc13f22a42b2.PNG)

As shown in the picture, there is horizontal scroll bar, which was not there. Its because of the width given to the footer. I will work on this issue @Raghwendra-Dey  Sir. Please assign it to me.

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 please go ahead. I have also mentioned this in #41 . Okay you do it. I would remove it from there.
This was introduced after #38 . You may look at the files changed in that PR.
