### ISSUE TITLE
Unstrike the todolist entry when unchecked

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#47]
When an entry is checked in its checkbox, then it gets striked off, but if the user unchecks that entry later, it doesn't gets unstricked.
Also, if the textbox is empty, and it is tried to be ticked, then it should simply do nothing, rather than stricking the background text `Enter TaskName`. Please make necessary amendments.

**Comment by Raghwendra-Dey** [comment]
@Ishan-Saini you have worked on this part. Would you like to take it up?

**Comment by Ishan-Saini** [comment]
@Raghwendra-Dey Yeah sure!
