### ISSUE TITLE
Design a logo for the project

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#48]
If anyone have worked with vector graphs softwares like Adobe Illustrator, Inkscape, etc, or maybe even photoshop or some drawing softwares, Or would like to learn them, and make something with it, then please design a cool logo for this project. The end user of this product are programmers like us, so keep this in mind while designing the logo. You can have a look [here](https://www.xypnox.com/blag/posts/designing-a-poster/). But this article deals with posters, and not logos. For logos special consideration is that, it should be compact, since its generally small and have little scope for detailing.

**Comment by inumausam** [comment]
I will be happy to learn and try this @Raghwendra-Dey

**Comment by devsTudu** [comment]
Hello my senior brother, Can I try to impress you with some of my logo design .

**Comment by Raghwendra-Dey** [comment]
@inumausam and @devsTudu you both try to do it. Atlast we can decide on which one to use, by a poll among the community.
Even if your design is not used, still you would end up learning the process of designing a logo.

**Comment by Raghwendra-Dey** [comment]
> Hello my senior brother, Can I try to impress you with some of my logo design .

And @devsTudu please follow the code of conduct of opensource while commenting.

**Comment by inumausam** [comment]
![new](https://user-images.githubusercontent.com/75451148/101953776-fd3a2b80-3c20-11eb-8b39-d7de37ed86e3.png)
how is it @Raghwendra-Dey

**Comment by Raghwendra-Dey** [comment]
Hey @inumausam that looks great!! I think, if you could replace that book with a speedometer kind of thing, it may look better. Could you please it once?

**Comment by devsTudu** [comment]
Check this out @Raghwendra-Dey  

![20201212_100112_0000](https://user-images.githubusercontent.com/65746343/101975382-3a72dd80-3c62-11eb-979b-501874f9c6ce.png)

**Comment by inumausam** [comment]
yaa sure I will have a look at it

**Comment by inumausam** [comment]
![tre](https://user-images.githubusercontent.com/75451148/101977261-54b4b780-3c72-11eb-9ae7-fd026e499ac2.png)
 @Raghwendra-Dey

**Comment by inumausam** [comment]
if the logo part is ok then can i create a pull request for this and start working on the dismissible read me message at the top. @Raghwendra-Dey

**Comment by Raghwendra-Dey** [comment]
@devsTudu I think your logo is also quite good. Please you also create a PR to add the logo in the `assets` folder. Later we would look which one suits better in the actual design, and put that up. Till then, let both of them be in the repo.
