### ISSUE TITLE
Second Timer loses control

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#5]
Follow these steps, to reproduce the error:

1. `Switch on` the `second timer`, keeping `first` one is still `off`
2. After that let the `second timer` to run for few seconds 
3. Then `first timer` is `switched on` (which is internally coupled with the `second timer`, i.e. it `switches on` the `second timer` everytime it `switches on` itself and vice versa due to #3, but in this case this coupling is of no use, since the `second timer` is already running), 
4. And after this event, the `second timer` loses control, i.e. after this event you can't `switch off` or `clear`, or do anything with the second timer, which is a bug. Try to `switch off` the `second timer` now, it won't `switch off`.

Anyhow, after resolving #4, this bug would be gone, but i doubt that this thing might be due to some other logic fault which might pop up later, so better to remove it now only.

**Comment by rsriramc** [comment]
I am interested to take up on this.
I have found a bug which may not be resolved by solving the issue #4

**Comment by Raghwendra-Dey** [comment]
@ravisrc yeah please go ahead. Please explain about the bug you found which is unresolvable even after #4.
