### ISSUE TITLE
add code_of_conduct.md file

### ISSUE THREAD

**Issue by tejan-singh** [Raghwendra-Dey/productivity_meter#52]
- The repository is missing necessary code of conduct file.

**Comment by Raghwendra-Dey** [comment]
We don't have any specific code of conduct as such. We just try to follow the general code of conduct of opensource.

**Comment by tejan-singh** [comment]
Yes. That's what I am trying to add. All GitHub projects have code of conduct file.

**Comment by tejan-singh** [comment]
Its nice to have one for open source projects.

**Comment by Vishal-raj-1** [comment]
Do you want to close this issue for now ?? @Raghwendra-Dey

**Comment by Raghwendra-Dey** [comment]
I don't think for small and developmental projects like this, we should be wasting time in code of conduct things. We can always do this later, when our product is almost ready.

**Comment by Vishal-raj-1** [comment]
> I don't think for small and developmental projects like this, we should be wasting time in code of conduct things. We can always do this later, when our product is almost ready.

yep!!
