### ISSUE TITLE
Make the Todo list scrollbar appear only when required

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#53]
Make the Scrollbar of ToDo list only appear when its required, i.e. when the number of entries overflows the visible height of the list.

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu You have worked on the boilerplate code of this. Would you like to take this up?

**Comment by Vishal-raj-1** [comment]
@Raghwendra-Dey may I get started with this issue ??

**Comment by Raghwendra-Dey** [comment]
@Vishal-raj-1 okay! please go ahead!!

**Comment by Bbiswabasu** [comment]
> Make the Scrollbar of ToDo list only appear when its required, i.e. when the number of entries overflows the visible height of the list.

For me, it is showing scrollbar only when no of entries overflow. Can you plz make it more clear which part you are talking about.

**Comment by Vishal-raj-1** [comment]
> For me, it is showing scrollbar only when no of entries overflow. Can you plz make it more clear which part you are talking about.

![tofo](https://user-images.githubusercontent.com/59874304/101907378-7ebd9980-3be0-11eb-8c4e-d715afa80cb1.JPG)

**Comment by Raghwendra-Dey** [comment]
> > Make the Scrollbar of ToDo list only appear when its required, i.e. when the number of entries overflows the visible height of the list.
> 
> For me, it is showing scrollbar only when no of entries overflow. Can you plz make it more clear which part you are talking about.

Actually I was talking about removing the white line which is there even when the number of entries is lesser than the overflow.

**Comment by Bbiswabasu** [comment]
> 
> > For me, it is showing scrollbar only when no of entries overflow. Can you plz make it more clear which part you are talking about.
> 
> ![tofo](https://user-images.githubusercontent.com/59874304/101907378-7ebd9980-3be0-11eb-8c4e-d715afa80cb1.JPG)
> 

Okay. Actually I just checked it on my phone and there was no such problem.

**Comment by Vishal-raj-1** [comment]
I have solved this issue !! I will create a PR shortly.!!
