### ISSUE TITLE
Give styling to the ToDo list

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#54]
currently the Todo list `cross` button has no styling. Also the dimentions of the entries looks very odd, its too big. Also, the checkbox is too small. Correct these things, and give it a decent dimentions, along with styling it.

**Comment by ghost** [comment]
@Raghwendra-Dey  Sir, I can work on this issue. It looks odd to me too.

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 please go ahead.

**Comment by Raghwendra-Dey** [comment]
Please style the text `ToDo` as well. Maybe use some other font/color, or anything.

**Comment by ghost** [comment]
Sure Sir

**Comment by ghost** [comment]
![diffTodoList](https://user-images.githubusercontent.com/63122133/101989456-658f1880-3cc6-11eb-8a65-57a93c42832d.PNG)

Anything other than this? @Raghwendra-Dey  Sir. Please suggest.

**Comment by Raghwendra-Dey** [comment]
Yeah, could you reduce the gap between two entry row a bit, it would look better maybe, and I think, if we reduce that gap, then maybe we can adjust more entries without using scrolling. Please post the photo after reducing the gap, and we'll decide, then you may go ahead with shooting a PR.

**Comment by ghost** [comment]
![todolist](https://user-images.githubusercontent.com/63122133/101990970-90ca3580-3ccf-11eb-8b4c-0d34fd092ea4.PNG)

I couldn't reduce the space but I did this. Now? @Raghwendra-Dey  Sir

**Comment by Raghwendra-Dey** [comment]
> ![todolist](https://user-images.githubusercontent.com/63122133/101990970-90ca3580-3ccf-11eb-8b4c-0d34fd092ea4.PNG)
> 
> I couldn't reduce the space but I did this. Now? @Raghwendra-Dey  Sir

Did what? How many entries could fit in now? Without scrolling?

Could you explain whats the problem you are facing in reducing that size, maybe we can help?

**Comment by ghost** [comment]
![todolist](https://user-images.githubusercontent.com/63122133/101992423-1dc5bc80-3cd9-11eb-92d1-7c8254f257fe.PNG)


Did that change @Raghwendra-Dey  Sir :fire:

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 cool!! Please update the changes to the PR. I'll review em tomorrow.

**Comment by ghost** [comment]
Done @Raghwendra-Dey  Sir

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/102691478-e607c900-4232-11eb-87e9-fc122b09676c.PNG)

@Raghwendra-Dey Sir, I have changed the todolist styling and also did the styling of record button. Please give feedback for it.

**Comment by Raghwendra-Dey** [comment]
Please post ss in both browsers, and also post the ss of the pressed state of `record` button.

**Comment by ghost** [comment]
@Raghwendra-Dey Sir In firefox and the pressed state of record button.

![Capture](https://user-images.githubusercontent.com/63122133/102692981-4ac82100-423d-11eb-8f28-593217d09536.PNG)

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 just a suggestion, I think a darker color, for the record pressed state would look better, Like it is now, in the deployed site.

**Comment by ghost** [comment]
Sure Sir.

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/102693728-b82a8080-4242-11eb-907b-940cad098d31.PNG)

Is this pressed state color Okay @Raghwendra-Dey Sir?

**Comment by Raghwendra-Dey** [comment]
And whats the released state?

**Comment by ghost** [comment]
The purple one is the normal state, the white one is the hovered state and the blue one is the pressed state.

**Comment by Raghwendra-Dey** [comment]
seems good. Make a PR, I would review it.

**Comment by ghost** [comment]
Okay @Raghwendra-Dey Sir.
