### ISSUE TITLE
Same Ids for different Element

### ISSUE THREAD

**Issue by Vishal-raj-1** [Raghwendra-Dey/productivity_meter#56]
Id is unique. We can't give **multiple ids to an element OR same id for multiple elements.** 
One more little thing I would like to mention is if it is centiseconds instead of miliseconds use `cs` instead of `ms`.

![id error](https://user-images.githubusercontent.com/59874304/101908719-81b98980-3be2-11eb-93c9-aa97bb9a1936.JPG)

I would like to work on this issue !! @Raghwendra-Dey Sir !!

**Comment by Raghwendra-Dey** [comment]
@Vishal-raj-1 we haven't given multiple ids for the same element right? Yeah, we have given multiple elements same ids, and thats wrong. You may correct it.

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 we haven't given multiple ids for the same element right? Yeah, we have given multiple elements same ids, and thats wrong. You may correct it.

Okay I am fixing that !!
