### ISSUE TITLE
Add a block to show difference of the two timers

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#6]
Add a new block, maybe similar in look with the two timers, with `Hours Minutes Seconds Centiseconds` sections, placed in between the two timers, to show the difference between the two timers, i.e. `Time Devoted - Actual Time Used`.
No need to handle the case of negative result, since that is a bug and would be fixed after #4 is fixed.
Keep in mind to orient the styling of the blocks accordingly while placing the difference block in between. You may need to tweak with the CSS a bit, and also change the positioning of the blocks. You may first draw your styling ideas, in some drawing software and we may discuss upon that, and then you may proceed for implementation.

**Comment by Bbiswabasu** [comment]
I would like to work on this
