### ISSUE TITLE
The pop-ups dont work

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#78]
Steps to reproduce the error:
* press `+1` button more than once(twice or thrice or ..) consecutively, without giving the pop-up time to fade away.
* Now, before it getting fade away, press the cross button on the pop-up.
* Now, if you again press the `+1` button any number of times, the pop-up for that wont function.

P.S: this is with all the four pop-ups, so the steps would be same, just replace the name of the button.

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna would you like to work on this, since you have worked on this part?

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey  Yes, will do so.

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey  Can you clarify which button name you are talking about. Sorry, I didn't get that.
