### ISSUE TITLE
Make the quotes bar showing alternating quotes, not only one

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#79]
Make the quote to be something which cycles through a set of maybe 3-4 quotes(make the number of quotes, variable and easy to add any quote anytime). With each quote appearing and getting removed using typerwriter effect, after staying for sometime in the screen. You can take help from [this repo](https://github.com/le4ker/personal-jekyll-theme) for implementing it. The effect I am proposing is exactly similar showing in this repo. Don't forget to shuffle the list of quotes, after every iteration throughout the list.

**Comment by rsriramc** [comment]
I would like to work on this
Just a small confirmation: what does variable quotes mean? Is it from the developer side or they have to be taken from the clients i,e, the users of this app

**Comment by Raghwendra-Dey** [comment]
@ravisrc The developer's side one. By variable I just meant that don't try to hard code that the quotes list would cycle through 4 quotes of the quotes list. It should be like if tomorrow I want to extend the quotes list by one quote, I should not need to mess around with the code, and just add that quote to that quotesList array, and I should be good to go.
