### ISSUE TITLE
Stop the flickering of the difference timer

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#8]
The difference timer is flickering sometimes, when both the timers are running at the same time, maybe because of very very small changes in consecutive difference measurements between the two clocks. It mainly visible on the `Centiseconds` part.
Let me know, if you have want some more explaination or any problems in coming up with a logic to get it done.

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu please look into this, if you would like to do it.

**Comment by Bbiswabasu** [comment]
Ok I will do this
