### ISSUE TITLE
Add a contributors section in the readme

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#81]
Add a contributors section in the readme using [all-contributors](https://github.com/all-contributors/all-contributors) specification. You can take help from [this](https://github.com/Graph-Visualization/graph-api) repo. The section needed is exactly similar to this.

**Comment by ghost** [comment]
@Raghwendra-Dey I can work on this and send the PR today itself

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 sure! you take this up. But try to also focus on the reviews on this: #73 .

**Comment by ghost** [comment]
@Raghwendra-Dey The way you are saying to do it will not be dynamic.

We can do it in this way it will be dynamic.
![Capture](https://user-images.githubusercontent.com/63122133/103139756-50d25d80-4694-11eb-9b57-3137caa752f2.PNG)

It will contain the github contributors link with it.

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 This also looks cool! Could you explain how you are planning to achieve this?
Also, could you also include the name of the person below that in this type of dynamic list?

**Comment by ghost** [comment]
This is a website where after giving the repo url u will get the contributors images.

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 can you look for ways to also add the contributors names below their images?

**Comment by ghost** [comment]
But it will not add the names of the contributors coming in future and also I have to do all this manually then.

**Comment by Raghwendra-Dey** [comment]
No actually I was saying to look for some alternative. Anyhow, if you can't find then make a PR with this only, thats also fine.

**Comment by Raghwendra-Dey** [comment]
Hey @urvashi-code1255 , if you didn't find any alternative, then please make a PR with this one only.

**Comment by ghost** [comment]
Sure @Raghwendra-Dey  I was justing waiting for my PR to get merged now I will make a PR for this

**Comment by Raghwendra-Dey** [comment]
okay!
