### ISSUE TITLE
Update the Average time/problem, even when -1 is pressed

### ISSUE THREAD

**Issue by Raghwendra-Dey** [Raghwendra-Dey/productivity_meter#82]
Currently the avg time/problem, is updated only when the +1 button, is pressed, but it doesn't do anything, when the -1 button is pressed. The problem was to save the delta time changes in the past problems, may blow up memory. But we may use a double ended Queue based solution for subtraction of one problem from the problem counter, and still showing the correct average time per problem. And keeping a max_capacity variable, and keep it to something like, 100, so, its highly unlikely, that a user would press -1 consecutively 100 times, And if the size of the deque becomes greater than the max_capacity, then pop-out elements from the front(which are the least recently used ones).
When the user presses -1 you would pop-out elements from the back, which are the recent time delta, and update the average accordingly, using that value.
If the deque is empty, then you may, do nothing. Later on we can implement a pop-up warning for the user, that `decreasing problem count further might result in faulty avg time`.

**Comment by Bbiswabasu** [comment]
I would like to work on this
